### ISSUE TITLE
Does not work with NextJS

### ISSUE THREAD

**Issue by jdudmesh** [uiwjs/react-md-editor#52] opened 2020-10-19 09:23 UTC
NextJS does not allow global CSS to be imported at the component level, only in _app.js.

```
error - ./node_modules/@uiw/react-md-editor/lib/esm/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm

```

See https://codesandbox.io/s/compassionate-cookies-msmsd?file=/pages/index.js

**Comment by jaywcjlove** [comment] 2020-10-19 11:28
https://stackoverflow.com/questions/60941853/next-js-global-css-cannot-be-imported-from-files-other-than-your-custom-app

@jdudmesh Whether it can solve the problem?

**Comment by diego9497** [comment] 2020-10-20 04:05
Doesn't work for me 
Next.Js team suggest [this to fix it](https://github.com/vercel/next.js/blob/master/errors/css-npm.md),  it could be possible?

**Comment by jdudmesh** [comment] 2020-10-20 09:55
The problem is that MDEditor.tsx has an import for index.less. The component will only work with NextJS if this import is removed. This requires changing react-md-editor. Consider moving the CSS for the component into a separate file which can be imported independently i.e. in _app.js.

**Comment by cjchirag7** [comment] 2020-10-21 10:54
I'm too facing the same problem, this doesn't work in NextJS. Any way to make it working ?

**Comment by earthnoob** [comment] 2020-10-26 09:17
I was having the exact problem and managed to fix by installing `@zeit/next-css` and updated `next.config.js`:

`
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  // Your configurations here
});
`

Hope that helps you, let me know if it works.

**Comment by diego9497** [comment] 2020-10-26 16:35
@earthnoob thanks it works for me.

**Comment by durancristhian** [comment] 2020-11-10 16:06
WOOO, thank you @earthnoob. The question now is: what's the difference between the plugin and the built-in configuration?

**Comment by cyphire** [comment] 2020-12-24 01:14
I would love to use this as well, but just trying to get by the sparse next.config.js information for next js I guess this probably is a no go for me using it in Nextjs.  Can anyone recommend a markdown editor that does work for next?

**Comment by jaywcjlove** [comment] 2020-12-30 11:37
@jdudmesh @cyphire  https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js

thank you @earthnoob.

**Comment by themastersoda** [comment] 2021-01-08 20:54
This does not solve the problem, it only works around it. In order to make it work as it should with next.js users need a way to import CSS by themselves instead of having it imported in the source code.

**Comment by drewhaines** [comment] 2021-01-15 17:14
I ran into a styling issue but I wasn't using next.js. My setup is Rails + React and the css for the editor wasn't loading properly. I created a plain css file and imported it separately and that solved my issue.

It's attached as a txt cause Github says they don't support uploading css files. Figured this might be helpful for anyone that is in my position and doesn't want to hunt down all the current styles.

[markdown_editor.txt](https://github.com/uiwjs/react-md-editor/files/5821970/markdown_editor.txt)

**Comment by s-ashutosh-b** [comment] 2021-03-02 11:52
Solution to >
`error - ./node_modules/@uiw/react-md-editor/lib/esm/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm`

In your next.js component or page, add this>
`
import '@uiw/react-md-editor/dist/markdown-editor.css'
import '@uiw/react-md-editor/lib/esm/components/DragBar/index.css'
import '@uiw/react-md-editor/lib/esm/components/TextArea/index.css'
import '@uiw/react-md-editor/lib/esm/components/Toolbar/index.css'
import '@uiw/react-md-editor/lib/esm/components/Toolbar/Child.css'
`

Then, go to `node_modules/@uiw/` and comment all imports of `.css` files. It will start working. It worked for me on `next 10.0.7`
:)

**Comment by veksen** [comment] 2021-03-16 23:16
The suggested solution is now deprecated by Zeit/Vercel. Consider a proper fix and not import the CSS in the node_modules :)

**Comment by karlhorky** [comment] 2021-03-23 17:54
@jaywcjlove should this be reopened?

**Comment by karlhorky** [comment] 2021-03-23 17:56
@jaywcjlove should this be reopened? Sseems like the Next.js recommendation is now to not use imports of CSS from `node_modules`...

**Comment by jaywcjlove** [comment] 2021-03-23 18:26
@karlhorky If the above does not work, try the following.

1. Customizing Babel Config : https://nextjs.org/docs/advanced-features/customizing-babel-config
2. Use [`babel-plugin-transform-remove-imports`](https://github.com/uiwjs/babel-plugin-transform-remove-imports)，Delete the CSS import in `node_module`.
3. Import css in your page. `import '@uiw/react-md-editor/dist/markdown-editor.css'`

**Comment by karlhorky** [comment] 2021-03-23 18:36
Hmm... step 2 fails for some reason (`babel.config.js` is not the problem - this is just a newer config format):

https://codesandbox.io/s/nextjs-example-react-md-editor-forked-bjmoi?file=/babel.config.js

Is there something misconfigured here?

**Comment by karlhorky** [comment] 2021-03-23 18:42
Ah maybe webpack is not configured to run the `babel-loader` in `node_modules`, that would make sense...

**Comment by jaywcjlove** [comment] 2021-03-24 01:50
@karlhorky 

If it doesn't work, you can only use it. [`@zeit/next-css`](https://www.npmjs.com/package/@zeit/next-css) I saw its implementation, but it was actually modifying the [webpack configuration](https://github.com/vercel/next-plugins/commit/ef6f626176d2b886bacba16391766b4a64f95073#diff-e00202ba0baed10b01d91275cfe51fd777a3ea0a97d1df13b2014972dcc2dd2b).

For Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/next.config.js:25-39

I don't want `@uiw/react-md-editor` to only run in nextjs.

**Comment by karlhorky** [comment] 2021-03-24 08:51
`@zeit/next-css` is deprecated though - and recommended against. So probably not a good direction.

**Comment by karlhorky** [comment] 2021-03-24 08:59
> I don't want `@uiw/react-md-editor` to only run in nextjs.

I understand this, that makes sense. I don't think it should only work in Next.js.

However, many libraries instruct the users to import CSS files themselves (which makes it more flexible as well, for users without `css-loader`).

For example, in [the Reach UI docs](https://reach.tech/styling):

```
// import the components
import { Menu, MenuButton, MenuList, MenuItem } from "@reach/menu-button";
// and the styles
import "@reach/menu-button/styles.css";
```

Maybe it would make sense to move the CSS imports out of files like [`/lib/esm/Editor.js`](https://unpkg.com/browse/@uiw/react-md-editor@2.1.10/lib/esm/Editor.js) and into your installation guide for users instead?

Maybe the upcoming v3 would be a good time to make this potentially breaking change...?

**Comment by stLoiz** [comment] 2021-03-26 14:17
@jaywcjlove Is there any update on this? As the @zeit/next-css is deprecated how can we use this library?

**Comment by jaywcjlove** [comment] 2021-03-26 15:01
@stLoiz Did not expect the best of both worlds solution.

**Comment by xuliang2019** [comment] 2021-04-04 17:27
1.Create a `/static folder` at the same level the /pages folder.
2. In that folder put your `.css` files
3. In your page components import `Head` and add a `<link />` to your CSS.

```
import React from 'react';
import Head from 'next/head';

export default () => (
  <div>
    <Head>
      <title>My styled page</title>
      <link href="/static/styles.css" rel="stylesheet" />
    </Head>
    <p className="some-class-name">
      Hello world!
    </p>
  </div>
)
```
Reference: [https://github.com/vercel/next.js/issues/299#issuecomment-263146962](url)

**Comment by karlhorky** [comment] 2021-04-04 17:40
@xuliang2019 I don't think this is a solution. There are two issues with that:

1. The issue is that the import `import MDEditor from '@uiw/react-md-editor'` will already fail in Next.js (because inside the `@uiw/react-md-editor` package, there is an import of a CSS file that is inside of `node_modules`, which Next.js does not support)
2. There is no longer a `/static` folder in Next.js - it is now called `/public`: https://nextjs.org/docs/basic-features/static-file-serving

**Comment by A7U** [comment] 2021-05-04 21:44
Any solution for this? I really want to use this for my app

**Comment by namnd** [comment] 2021-05-07 01:11
For anyone is still looking for a temporary solution, I've created a forked package out of this one https://www.npmjs.com/package/@namskiiiii/react-md-editor-naked just to remove the styling

**Comment by karlhorky** [comment] 2021-05-07 05:59
**Alternative Workaround**

If you don't want to use a fork / a different npm package, you can also achieve this with [`patch-package`](https://www.npmjs.com/package/patch-package), by making the same edit in your `node_modules` that @namnd did (see link below) and then running `yarn patch-package @uiw/react-md-editor`.

https://github.com/namnd/react-md-editor-naked/commit/e43c1778360fc86fed4d383c08931adfc1fa5964

**Comment by karlhorky** [comment] 2021-05-07 06:00
But it's not a final solution.

@jaywcjlove I would again recommend switching to get users to import the styles themselves:

https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-805623260

**Comment by serendipity1004** [comment] 2021-05-21 03:17
lol still not merged? it doesn't seem like an unreasonable approach tbh. SSR is not of something peculiar these days. Removing default import of css would be greatly appreciated.

**Comment by jaywcjlove** [comment] 2021-05-21 03:26
I haven't thought about it clearly.

After the change, my project must be changed. 

Obviously I am not very happy.  :(

@serendipity1004

**Comment by jaywcjlove** [comment] 2021-05-21 03:27
I don’t know if there is any way to meet my needs as well as your needs.

**Comment by serendipity1004** [comment] 2021-05-21 03:30
Yes. It's almost impossible to suit all the needs of so many frameworks these days and I thank you so much for taking time and effort to build a very beautiful open source. However, if you want your package to grow (I don't know if this is your intention) it would be a good idea to encapsulate NextJS users because it is one of the biggest SSR framework. I don't think this is something you should be unhappy about. You should be happy because it just means that your package is gaining a lot of popularity. That's why there are demands here and there.

**Comment by rafaelguedes** [comment] 2021-05-24 11:47
I agree with @serendipity1004. NextJS is one of the biggest SSR frameworks and I believe that not encapsulating its users will prevent this amazing package to grow. I'm also trying to make this work with NextJS and I'm struggling. 
Can you please merge the PR #131 assuming that it will fix this issue?

**Comment by jaywcjlove** [comment] 2021-05-26 15:52
I want to use [babel-plugin-transform-remove-imports](https://github.com/uiwjs/babel-plugin-transform-remove-imports) to remove the style file in node_modules.

Then load the style on the page.

@rafaelguedes I want to solve the problem in this way.

**Comment by rafaelguedes** [comment] 2021-05-26 16:02
And are you considering updating the repo with that change? 
@jaywcjlove

**Comment by jaywcjlove** [comment] 2021-05-26 17:27
I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.

Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js

@rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497 

```js
// next.config.js
const removeImports = require("next-remove-imports");

module.exports = removeImports({});
```

```js
// pages/index.js

import Head from 'next/head'
import MDEditor from '@uiw/react-md-editor';
import "@uiw/react-md-editor/dist/markdown-editor.css";
import "@uiw/react-markdown-preview/dist/markdown.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MDEditor value="**Hello world!!!**" />
    </div>
  )
}
```

**Comment by A7U** [comment] 2021-05-26 17:29
> 
> 
> I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.
> 
> Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js
> 
> @rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497
> 
> ```js
> // next.config.js
> const removeImports = require("next-remove-imports");
> 
> module.exports = removeImports({});
> ```
> 
> ```js
> // pages/index.js
> 
> import Head from 'next/head'
> import MDEditor from '@uiw/react-md-editor';
> import "@uiw/react-md-editor/dist/markdown-editor.css";
> import "@uiw/react-markdown-preview/dist/markdown.css";
> 
> export default function Home() {
>   return (
>     <div>
>       <Head>
>         <title>Create Next App</title>
>         <meta name="description" content="Generated by create next app" />
>         <link rel="icon" href="/favicon.ico" />
>       </Head>
>       <MDEditor value="**Hello world!!!**" />
>     </div>
>   )
> }
> ```

I'll try that out, thanks

**Comment by karlhorky** [comment] 2021-05-26 19:21
@jaywcjlove thanks for creating this :)

I couldn't see it clearly in the readme, but looking at the code linked below, it seems the default behavior of `next-remove-imports` is to remove all `.less` and `.css` imports from all packages in `node_modules`?

https://github.com/uiwjs/next-remove-imports/blob/939c95df719f33549715fff5c71281bedc6c6a76/index.js#L2-L3

Maybe it would make sense to also do the following (for anyone that is looking to use it):

- document this behavior in the `next-remove-imports` readme
- also support `.sass` and `.scss` by default?
- add Next.js usage instructions (eg. your code snippet above) to the `@uiw/react-md-editor` readme

**Closed** 2021-05-27 03:57 UTC

**Comment by jaywcjlove** [comment] 2021-05-28 02:11
I am sure [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) is a perfect solution. :)

**Comment by Dhenyson** [comment] 2021-06-08 16:09
Just to consolidate the solution: Yes, the current solution works! Even so I kept getting errors, but the reason was simply the wrong use of the "next-remove-imports" plugin, when I needed to export more than one module in next.config.js . I was forgetting to put "options" as argument to "next-remove-imports". I will put a clean and simple code for understanding.

**Wrong mode:**
```javascript
const removeImports = require('next-remove-imports')({});
                  
module.exports = removeImports({})

module.exports = {
     images: {
         domains: [
             'localhost',
             '10.0.0.164',
             'example.com'
         ]
     }
}
```

**Correct mode:**
```javascript
const removeImports = require('next-remove-imports')({})

module.exports = removeImports({
     images: {
         domains: [
             'localhost',
             '10.0.0.164',
             'example.com'
         ]
     }
})
```

**Comment by nizarfadlan** [comment] 2021-09-22 06:46
> 
> 
> @jdudmesh @cyphire https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js
> 
> thank you @earthnoob.

Not work for me

**Comment by nizarfadlan** [comment] 2021-09-22 07:12
> ```js
> import MDEditor from '@uiw/react-md-editor'
> ```

Not work for me, this error `require() of ES modules is not supported.`

**Comment by nizarfadlan** [comment] 2021-09-22 07:12
> 
> 
> > I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.
> > Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js
> > @rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497
> > ```js
> > // next.config.js
> > const removeImports = require("next-remove-imports");
> > 
> > module.exports = removeImports({});
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > // pages/index.js
> > 
> > import Head from 'next/head'
> > import MDEditor from '@uiw/react-md-editor';
> > import "@uiw/react-md-editor/dist/markdown-editor.css";
> > import "@uiw/react-markdown-preview/dist/markdown.css";
> > 
> > export default function Home() {
> >   return (
> >     <div>
> >       <Head>
> >         <title>Create Next App</title>
> >         <meta name="description" content="Generated by create next app" />
> >         <link rel="icon" href="/favicon.ico" />
> >       </Head>
> >       <MDEditor value="**Hello world!!!**" />
> >     </div>
> >   )
> > }
> > ```
> 
> I'll try that out, thanks

Not work for me `require() of ES modules is not supported.`

**Comment by nizarfadlan** [comment] 2021-09-22 07:29
> 
> 
> > > I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.
> > > Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js
> > > @rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497
> > > ```js
> > > // next.config.js
> > > const removeImports = require("next-remove-imports");
> > > 
> > > module.exports = removeImports({});
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```js
> > > // pages/index.js
> > > 
> > > import Head from 'next/head'
> > > import MDEditor from '@uiw/react-md-editor';
> > > import "@uiw/react-md-editor/dist/markdown-editor.css";
> > > import "@uiw/react-markdown-preview/dist/markdown.css";
> > > 
> > > export default function Home() {
> > >   return (
> > >     <div>
> > >       <Head>
> > >         <title>Create Next App</title>
> > >         <meta name="description" content="Generated by create next app" />
> > >         <link rel="icon" href="/favicon.ico" />
> > >       </Head>
> > >       <MDEditor value="**Hello world!!!**" />
> > >     </div>
> > >   )
> > > }
> > > ```
> > 
> > 
> > I'll try that out, thanks
> 
> Not work for me `require() of ES modules is not supported.`

Can only display, but can not type

**Comment by matteoturini** [comment] 2021-09-27 21:17
@jaywcjlove Can you just remove the imports from your package, and ask us to import it ourselves? Your solution with `next-remove-imports` is not working for me.

**Comment by tawnyzhao** [comment] 2021-10-06 02:45
> 
> 
> > > I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.
> > > Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js
> > > @rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497
> > > ```js
> > > // next.config.js
> > > const removeImports = require("next-remove-imports");
> > > 
> > > module.exports = removeImports({});
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```js
> > > // pages/index.js
> > > 
> > > import Head from 'next/head'
> > > import MDEditor from '@uiw/react-md-editor';
> > > import "@uiw/react-md-editor/dist/markdown-editor.css";
> > > import "@uiw/react-markdown-preview/dist/markdown.css";
> > > 
> > > export default function Home() {
> > >   return (
> > >     <div>
> > >       <Head>
> > >         <title>Create Next App</title>
> > >         <meta name="description" content="Generated by create next app" />
> > >         <link rel="icon" href="/favicon.ico" />
> > >       </Head>
> > >       <MDEditor value="**Hello world!!!**" />
> > >     </div>
> > >   )
> > > }
> > > ```
> > 
> > 
> > I'll try that out, thanks
> 
> Not work for me `require() of ES modules is not supported.`

This snippet was broken after `3.4.11`

**Comment by jaywcjlove** [comment] 2021-10-06 13:38
@matteoturini The example still works: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js

```js
"dependencies": {
  "@uiw/react-md-editor": "3.6.5",
  "next": "11.1.2",
  "next-remove-imports": "1.0.6",
  "react": "17.0.2",
  "react-dom": "17.0.2"
},
```

**Comment by jaywcjlove** [comment] 2021-10-22 02:51
@tawnyzhao 

- https://github.com/vercel/next.js/issues/9607

**Comment by dogukanakkaya** [comment] 2022-05-27 20:07
None of the solutions above not working with Next 12 and React 18.

**Comment by a-m-dev** [comment] 2022-07-09 09:01
I just wanted to drop a quick heads up on style imports! it looks like they are not bundled with this name any more: 
```tsx
import "@uiw/react-md-editor/dist/markdown-editor.css";
import "@uiw/react-markdown-preview/dist/markdown.css";
```

instead, they are: 
```tsx
import "@uiw/react-md-editor/dist/mdeditor.min.css";
import "@uiw/react-markdown-preview/dist/markdown.min.css";
```
here is a screenshot of dist folder inside of node-modules that got me for 2 mins to figure it out:

![Screenshot 2022-07-09 at 11 00 25](https://user-images.githubusercontent.com/29652890/178099242-42de2067-a637-4eae-8d4d-724b050bd9ed.png)

**Comment by bdugg9119** [comment] 2022-10-08 16:11
> I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.
> 
> Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js
> 
> @rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497
> 
> [![Open in CodeSandbox](https://camo.githubusercontent.com/6c555025d1974e87fe5422c60618c2f3a204cd525b69b22be590dc077fe3f6c1/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4f70656e253230696e2d436f646553616e64626f782d626c75653f6c6f676f3d636f646573616e64626f78)](https://codesandbox.io/embed/nextjs-example-react-md-editor-qjhn7?fontsize=14&hidenavigation=1&theme=dark) [![Open in StackBlitz](https://camo.githubusercontent.com/46c710d5b8fb34625bb2beff4fb6e1ff42b5a06e8c9445d4b2d93fbf4e1a85b0/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4f70656e253230496e2d537461636b426c69747a2d677265656e)](https://stackblitz.com/edit/nextjs-react-md-editor?embed=1&file=pages/index.js&hideExplorer=1&hideNavigation=1&theme=dark)
> 
> ```shell
> npm i @uiw/react-md-editor@v3.6.0
> npm i next-remove-imports
> ```
> 
> ```js
> // next.config.js
> const removeImports = require("next-remove-imports")();
> 
> module.exports = removeImports({
>   // ✅  options...
> });
> ```
> 
> ```js
> import "@uiw/react-md-editor/markdown-editor.css";
> import "@uiw/react-markdown-preview/markdown.css";
> import dynamic from "next/dynamic";
> import { useState } from "react";
> 
> const MDEditor = dynamic(
>   () => import("@uiw/react-md-editor").then((mod) => mod.default),
>   { ssr: false }
> );
> const EditerMarkdown = dynamic(
>   () =>
>     import("@uiw/react-md-editor").then((mod) => {
>       return mod.default.Markdown;
>     }),
>   { ssr: false }
> );
> 
> function HomePage() {
>   const [value, setValue] = useState("**Hello world!!!**");
>   return (
>     <div data-color-mode="dark">
>       <MDEditor value={value} onChange={setValue} />
>       <div style={{ paddingTop: 50 }}>
>           <EditerMarkdown source={value} />
>       </div>
>     </div>
>   );
> }
> 
> export default HomePage;
> ```
> 
> * [Support ES module format (ESM) in next.config.js vercel/next.js#9607](https://github.com/vercel/next.js/issues/9607)
> 
> * [Cannout build production Nextjs #350 (comment)](https://github.com/uiwjs/react-md-editor/issues/350#issuecomment-1042629304)
> 
> @pascuflow example: https://codesandbox.io/s/nextjs-example-react-md-editor-forked-89jwvb?file=/pages/index.js
> 
> ```diff
> - import { commands } from "@uiw/react-md-editor";
> + import * as commands from "@uiw/react-md-editor/esm/commands";
> ```

I used the plugin but I'm still encountering an error. The editor/preview seems to work fine when I navigate to the page with it via `<Link />`, however if I refresh that page I get the following error:

```
Server Error
require() of ES Module /home/axel/dev/lit-app/node_modules/react-markdown/index.js from /home/axel/dev/lit-app/node_modules/@uiw/react-markdown-preview/lib/index.js not supported.
Instead change the require of /home/axel/dev/lit-app/node_modules/react-markdown/index.js in /home/axel/dev/lit-app/node_modules/@uiw/react-markdown-preview/lib/index.js to a dynamic import() which is available in all CommonJS modules.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Comment by jaywcjlove** [comment] 2022-10-08 16:14
@jdudmesh 
- https://github.com/uiwjs/react-md-editor/issues/438#issuecomment-1265715896

**Comment by jaywcjlove** [comment] 2022-10-21 07:22
@jdudmesh 

- https://github.com/uiwjs/react-md-editor/issues/446#issue-1417594634

**Comment by Kartikgondha** [comment] 2023-02-06 06:22
solutions are 👍 

install :-
npm install next-remove-imports
npm install @uiw/react-md-editor@v3.6.0

// next.config.js file write :-
const removeImports = require('next-remove-imports')();
module.exports = removeImports({});


//File :- 
import "@uiw/react-md-editor/markdown-editor.css";
import "@uiw/react-markdown-preview/markdown.css";
import dynamic from "next/dynamic";
import { useState } from "react";

const MDEditor = dynamic(
  () => import("@uiw/react-md-editor"),
  { ssr: false }
);

function Pages() {
  const [value, setValue] = useState("**Hello world!!!**");
  return (
    <div>
      <MDEditor value={value} onChange={setValue} />
    </div>
  );
}

export default Pages;

**Comment by hypervillain** [comment] 2023-02-13 18:35
If you use several Next plugins, don't call it right away:

```
const withRemoveImports = require('next-remove-imports');
module.exports = withRemoveImports(withVanillaExtract(nextConfig));
````

**Comment by hypervillain** [comment] 2023-02-13 20:05
To use it with other Next plugins, don't call the function right away:

```
const withRemoveImports = require('next-remove-imports')
module.exports = withVanillaExtract(withRemoveImports(nextConfig))
````

**Comment by preetpatel** [comment] 2023-05-23 01:30
What worked for me (Next.js version 13.4.3) is inside your next.config.mjs add the following to your config:
```
...
experimental: {
    esmExternals: 'loose',
  },
....
```

**Comment by akash-mahmud** [comment] 2023-07-06 06:54
> solutions are 👍
> 
> install :- npm install next-remove-imports npm install @uiw/react-md-editor@v3.6.0
> 
> // next.config.js file write :- const removeImports = require('next-remove-imports')(); module.exports = removeImports({});
> 
> //File :- import "@uiw/react-md-editor/markdown-editor.css"; import "@uiw/react-markdown-preview/markdown.css"; import dynamic from "next/dynamic"; import { useState } from "react";
> 
> const MDEditor = dynamic( () => import("@uiw/react-md-editor"), { ssr: false } );
> 
> function Pages() { const [value, setValue] = useState("**Hello world!!!**"); return (
> 
> 
> 
> 
> );
> }
> export default Pages;

After doing all of these I am getting now webpack errors. 

`[BABEL] Note: The code generator has deoptimised the styling of /Users/md.redoanurrahmanrafi/Desktop/Development/projects/Matteo/Neurge/admin/node_modules/.pnpm/@mui+icons-material@5.11.9_@mui+material@5.11.10_@types+react@18.0.28_react@18.2.0/node_modules/@mui/icons-material/esm/index.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/md.redoanurrahmanrafi/Desktop/Development/projects/Matteo/Neurge/admin/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js as it exceeds the max of 500KB.
[BABEL] Note: The code generator has deoptimised the styling of /Users/md.redoanurrahmanrafi/Desktop/Development/projects/Matteo/Neurge/admin/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.`

I am using nextjs 13.x

**Comment by kambhani** [comment] 2023-07-19 06:29
For those struggling, I was able to fix this issue without installing `next-remove-imports` by adding the line `transpilePackages: ['react-md-editor']` to my `next.config.js` file.

**Comment by mahdisoultana** [comment] 2023-07-27 10:27
i got types error with typescript .
<img width="960" alt="ice_screenshot_20230727-112721" src="https://github.com/uiwjs/react-md-editor/assets/67097548/1f6b63e1-492e-4693-b547-25db90892672">

**Comment by veksen** [comment] 2023-07-27 10:50
> i got types error with typescript .
> 
> <img width="960" alt="ice_screenshot_20230727-112721" src="https://github.com/uiwjs/react-md-editor/assets/67097548/1f6b63e1-492e-4693-b547-25db90892672">
> 
> 

Rename your file to .tsx like the rest of your components - unrelated to this issue however

**Comment by felipe1120gomez** [comment] 2023-09-25 23:58
As @preetpatel mentioned the only thing you have to do is use:

```
experimental: {
    esmExternals: 'loose',
  },
```

Here I leave the code that I used in a NextJS 13.0.7 App:

next.config.js

```
// @ts-check
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',   /* This is not part of the react-md-editor configuration */
  reactStrictMode: true,   /* This is not part of the react-md-editor configuration */
  swcMinify: true,   /* This is not part of the react-md-editor configuration */
  experimental: {
    appDir: true,   /* This is not part of the react-md-editor configuration */
    esmExternals: 'loose',   /* For react-md-editor */
  },
  },
};

module.exports = nextConfig;
```

page.tsx (Component)

```
'use client';
import MDEditor, { commands } from '@uiw/react-md-editor';
import { ChangeEvent, useState } from 'react';

/* Custom button in toolbar */
const help = {
  name: 'help',
  keyCommand: 'help',
  buttonProps: { 'aria-label': 'Insert help' },
  icon: (
    <svg viewBox='0 0 16 16' width='12px' height='12px'>
      <path
        d='M8 0C3.6 0 0 3.6 0 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8Zm.9 13H7v-1.8h1.9V13Zm-.1-3.6v.5H7.1v-.6c.2-2.1 2-1.9 1.9-3.2.1-.7-.3-1.1-1-1.1-.8 0-1.2.7-1.2 1.6H5c0-1.7 1.2-3 2.9-3 2.3 0 3 1.4 3 2.3.1 2.3-1.9 2-2.1 3.5Z'
        fill='currentColor'
      />
    </svg>
  ),
  // eslint-disable-next-line no-unused-vars
  execute: (state: any, api: any) => {
    window.open('https://www.markdownguide.org/basic-syntax/', '_blank');
  },
};

export default function Page() {
  const [value, setValue] = useState<string | undefined>('**Hello world!!!**');

  const handleChange = (
    value?: string | undefined,
    // eslint-disable-next-line no-unused-vars
    event?: ChangeEvent<HTMLTextAreaElement> | undefined,
  ) => {
    setValue(value);
    console.log('markdown: ', value);
  };

  return (
    <div>
      <MDEditor
        value={value}
        onChange={handleChange}
        commands={[...commands.getCommands(), help]}
      />
      {/* (val) => setValue(val) */}
    </div>
  );
}
```

As you can see there is no need to install additional packages like next-remove-imports or use specific NextJS imports for the component.

**Comment by xairoo** [comment] 2024-01-21 09:11
Will this work in Next.js v14? Looks like it doesn't. Have tested all those different solutions in this issue, but no success. Anyway, Next.js broke so many things with every new version, that's impressive ;-)

**Comment by hanna244** [comment] 2024-07-11 00:53
> I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.
> 
> Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js Example: [@uiwjs/next-remove-imports/example](https://github.com/uiwjs/next-remove-imports/tree/main/example) Example: https://next-remove-imports-example.vercel.app
> 
> > ⚠️ https://www.npmjs.com/package/next-transpile-modules
> 
> @rafaelguedes @serendipity1004 @karlhorky @namnd @A7U @stLoiz @veksen @earthnoob @jdudmesh @diego9497
> 
> [![Open in CodeSandbox](https://camo.githubusercontent.com/9d60d033ee3a2f7807db8621b510700b6ec7e74ab08b75b352b445afa58d70e2/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4f70656e253230696e2d436f646553616e64626f782d626c75653f6c6f676f3d636f646573616e64626f78)](https://codesandbox.io/embed/nextjs-example-react-md-editor-qjhn7?fontsize=14&hidenavigation=1&theme=dark) [![Open in StackBlitz](https://camo.githubusercontent.com/2d1260876d3a905c14410ced58fc6886850b6f5d0bd6b40cd503a28170c8423c/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4f70656e253230496e2d537461636b426c69747a2d677265656e)](https://stackblitz.com/edit/nextjs-react-md-editor?embed=1&file=pages/index.js&hideExplorer=1&hideNavigation=1&theme=dark)
> 
> ```shell
> npm i @uiw/react-md-editor@v3.6.0
> npm i next-remove-imports
> ```
> 
> ```js
> // next.config.js
> const removeImports = require("next-remove-imports")();
> 
> module.exports = removeImports({
>   // ✅  options...
> });
> ```
> 
> ```js
> import "@uiw/react-md-editor/markdown-editor.css";
> import "@uiw/react-markdown-preview/markdown.css";
> import dynamic from "next/dynamic";
> import { useState } from "react";
> 
> const MDEditor = dynamic(
>   () => import("@uiw/react-md-editor").then((mod) => mod.default),
>   { ssr: false }
> );
> const EditerMarkdown = dynamic(
>   () =>
>     import("@uiw/react-md-editor").then((mod) => {
>       return mod.default.Markdown;
>     }),
>   { ssr: false }
> );
> 
> function HomePage() {
>   const [value, setValue] = useState("**Hello world!!!**");
>   return (
>     <div data-color-mode="dark">
>       <MDEditor value={value} onChange={setValue} />
>       <div style={{ paddingTop: 50 }}>
>           <EditerMarkdown source={value} />
>       </div>
>     </div>
>   );
> }
> 
> export default HomePage;
> ```
> 
> * [Support ES module format (ESM) in next.config.js vercel/next.js#9607](https://github.com/vercel/next.js/issues/9607)
> * [Errors regarding package use in Next.js + Typescript project due to module conflict #438](https://github.com/uiwjs/react-md-editor/issues/438)
> * [Using next-remove-imports but still can't deploy - Next.js #224](https://github.com/uiwjs/react-md-editor/issues/224)
> * [Cannout build production Nextjs #350](https://github.com/uiwjs/react-md-editor/issues/350)
> * [Editor reloads with state change in Next JS #422](https://github.com/uiwjs/react-md-editor/issues/422)
> 
> * [Cannout build production Nextjs #350 (comment)](https://github.com/uiwjs/react-md-editor/issues/350#issuecomment-1042629304)
> 
> ```diff
> + import * as commands from "@uiw/react-md-editor/lib/commands";
> - import { commands } from "@uiw/react-md-editor"
> - // or
> - import * as commands from "@uiw/react-md-editor/esm/commands";
> ```
> 
> example: https://codesandbox.io/s/nextjs-example-react-md-editor-forked-89jwvb?file=/pages/index.js
> 
> ```js
> import * as commands from "@uiw/react-md-editor/lib/commands";
> ```
> 
> ```diff
> import { MDEditorProps } from '@uiw/react-md-editor';
> import * as commands from '@uiw/react-md-editor/esm/commands';
> 
> + const MDEditor = dynamic<MDEditorProps>(() => import('@uiw/react-md-editor'), {
> +   ssr: false,
> + });
> 
> function HomePage() {
> -  const MDEditor = dynamic<MDEditorProps>(() => import('@uiw/react-md-editor'), {
> -    ssr: false,
> -  });
>   return (
>     <div>
>       <MDEditor
>          value="**Hello world!!!**"
>          commands={[
>            commands.bold,
>            commands.italic,
>          ]}
>       />
>     </div>
>   );
> }
> ```

You can use 'next-transpile-modules' instead of 'next-remove-imports'.

```
// next.config.mjs
import withTM from 'next-transpile-modules'

const WithTM = withTM(['@uiw/react-md-editor', '@uiw/react-markdown-preview'])

const nextConfig = {
   ...
}

export default WithTM(nextConfig)
```
